### ISSUE TITLE
Iwslt14 data set results are poor

### ISSUE THREAD

**Issue by wnntju** [jungokasai/deep-shallow#6]
Iwslt14 data (it is obtained from the data processing script in Fairseq, which is on knowledge distillation for this dataset. There is only 4.2 BLEU on this method. Is there no knowledge distillation? Why does this happen?

**Comment by jungokasai** [comment]
Huh, that seems strange. My guess is that IWSLT14 is an "easier" dataset, though I haven't experimented with it. Could you share with me what you exactly did? Like what dataset/training commands did you use?
